namespace Fixtures

open System

module Stub =

    let internal avatarGamblingHandSink(_) = raise (NotImplementedException "")
    let internal avatarGamblingHandSource(_) = raise (NotImplementedException "")
    let internal avatarInventorySink(_)=raise (NotImplementedException "") 
    let internal avatarInventorySource(_)=raise (NotImplementedException "") 
    let internal avatarIslandFeatureSink (_)=raise (NotImplementedException "") 
    let internal avatarIslandFeatureSource (_)=raise (NotImplementedException "")
    let internal avatarIslandSingleMetricSink(_)=raise (NotImplementedException "") 
    let internal avatarIslandSingleMetricSource(_)=raise (NotImplementedException "") 
    let internal avatarJobSink(_)=raise (NotImplementedException "") 
    let internal avatarJobSource(_)=raise (NotImplementedException "") 
    let internal avatarMessagePurger(_)=raise (NotImplementedException "") 
    let internal avatarMessageSink(_)=raise (NotImplementedException "") 
    let internal avatarMessageSource(_)=raise (NotImplementedException "")
    let internal avatarMetricSource(_)=raise (NotImplementedException "")
    let internal avatarShipmateSource(_)=raise (NotImplementedException "") 
    let internal avatarSingleMetricSink(_)=raise (NotImplementedException "") 
    let internal avatarSingleMetricSource(_)=raise (NotImplementedException "") 
    let internal commoditySource(_)=raise (NotImplementedException "") 
    let internal epochSecondsSource(_)=raise (NotImplementedException "")
    let internal islandFeatureGeneratorSource(_)=raise (NotImplementedException "") 
    let internal islandFeatureSource(_)=raise (NotImplementedException "")
    let internal islandItemSink(_)=raise (NotImplementedException "") 
    let internal islandItemSource(_)=raise (NotImplementedException "") 
    let internal islandJobPurger(_)=raise (NotImplementedException "") 
    let internal islandJobSink(_)=raise (NotImplementedException "") 
    let internal islandJobSource(_)=raise (NotImplementedException "") 
    let internal islandLocationByNameSource(_)=raise (NotImplementedException "") 
    let internal islandMarketSink(_)=raise (NotImplementedException "") 
    let internal islandMarketSource(_)=raise (NotImplementedException "") 
    let internal islandSingleFeatureSink (_)=raise (NotImplementedException "")
    let internal islandSingleFeatureSource (_)=raise (NotImplementedException "")
    let internal islandSingleJobSource(_)=raise (NotImplementedException "") 
    let internal islandSingleMarketSink(_)=raise (NotImplementedException "") 
    let internal islandSingleMarketSource(_)=raise (NotImplementedException "") 
    let internal islandSingleNameSink(_)=raise (NotImplementedException "") 
    let internal islandSingleNameSource(_)=raise (NotImplementedException "") 
    let internal islandSingleStatisticSink(_)=raise (NotImplementedException "") 
    let internal islandSingleStatisticSource(_)=raise (NotImplementedException "") 
    let internal islandSource(_)=raise (NotImplementedException "") 
    let internal islandStatisticTemplateSource(_)=raise (NotImplementedException "") 
    let internal itemSingleSource(_)=raise (NotImplementedException "")
    let internal itemSource(_)=raise (NotImplementedException "") 
    let internal random (_)=raise (NotImplementedException "")
    let internal rationItemSource(_)=raise (NotImplementedException "") 
    let internal shipmateRationItemSink(_)=raise (NotImplementedException "") 
    let internal shipmateRationItemSource(_)=raise (NotImplementedException "") 
    let internal shipmateSingleStatisticSink(_)=raise (NotImplementedException "") 
    let internal shipmateSingleStatisticSource(_)=raise (NotImplementedException "") 
    let internal shipmateStatisticTemplateSource(_)=raise (NotImplementedException "") 
    let internal switchSource(_)=raise (NotImplementedException "")
    let internal termNameSource(_)=raise (NotImplementedException "") 
    let internal termSources(_)=raise (NotImplementedException "") 
    let internal vesselSingleStatisticSink(_)=raise (NotImplementedException "") 
    let internal vesselSingleStatisticSource(_)=raise (NotImplementedException "") 
    let internal vesselStatisticSink(_)=raise (NotImplementedException "") 
    let internal vesselStatisticTemplateSource(_)=raise (NotImplementedException "") 
    let internal worldSingleStatisticSource (_)=raise (NotImplementedException "")



