namespace Splorr.Seafarers.Services

open Splorr.Common

type ServiceContext =
    inherit CommonContext
    inherit Avatar.SetJobContext
    inherit AvatarGamblingHand.GetContext
    inherit AvatarGamblingHand.SetContext
    inherit AvatarInventory.GetInventoryContext
    inherit AvatarInventory.SetInventoryContext
    inherit AvatarIslandFeature.GetFeatureContext
    inherit AvatarIslandFeature.SetFeatureContext
    inherit AvatarIslandMetric.GetContext
    inherit AvatarIslandMetric.PutContext
    inherit AvatarJob.GetContext
    inherit AvatarMessages.AddContext
    inherit AvatarMessages.GetContext
    inherit AvatarMetric.GetMetricContext
    inherit AvatarMetric.SetMetricContext
    inherit AvatarShipmates.GetShipmatesContext
    inherit Commodity.GetCommoditiesContext
    inherit Island.GetCommoditiesContext
    inherit Island.GetIslandItemsContext
    inherit Island.GetIslandMarketContext
    inherit Island.GetFeaturesContext
    inherit Island.HasFeatureContext
    inherit Island.PutCommoditiesContext
    inherit Island.PutIslandItemsContext
    inherit Island.PutIslandMarketContext
    inherit Island.GetListContext
    inherit Island.GetStatisticContext
    inherit Island.GetStatisticTemplatesContext
    inherit Island.SetIslandStatisticContext
    inherit IslandJob.AddContext
    inherit IslandJob.GetContext
    inherit IslandJob.PurgeContext
    inherit IslandMarket.DeterminePriceContext
    inherit IslandName.GetNameContext
    inherit IslandVisit.EpochSecondsSourceContext
    inherit Item.GetContext
    inherit Item.GetListContext
    inherit Job.CreateContext
    inherit Shipmate.GetGlobalRationItemsContext
    inherit Shipmate.GetStatisticTemplatesContext
    inherit Shipmate.SetRationItemsContext
    inherit ShipmateStatistic.GetContext
    inherit ShipmateStatistic.PutContext
    inherit Utility.GetTermsContext
    inherit Utility.RandomContext
    inherit Vessel.GetStatisticContext
    inherit Vessel.GetStatisticTemplateContext
    inherit Vessel.SetStatisticContext
    inherit WorldCreation.GenerateIslandFeatureContext
    inherit WorldCreation.SetIslandFeatureContext
    inherit WorldCreation.SetIslandNameContext
    inherit WorldExport.SaveContext
    inherit WorldIslands.GetIslandByNameContext
    inherit WorldIslands.GetIslandJobContext
    inherit WorldMessages.ClearMessagesContext
    inherit WorldStatistic.GetStatisticContext

